// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkTimeTracker.Data;

#nullable disable

namespace WorkTimeTracker.Data.Migrations
{
    [DbContext(typeof(WorkTimeContext))]
    [Migration("20251117123003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WorkTimeTracker.Models.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stanowisko")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StawkaGodzinowa")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("WorkTimeTracker.Models.RejestrCzasu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyNadgodziny")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyUrlop")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LiczbaGodzin")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PracownikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId");

                    b.ToTable("Rejestry");
                });

            modelBuilder.Entity("WorkTimeTracker.Models.RejestrCzasu", b =>
                {
                    b.HasOne("WorkTimeTracker.Models.Pracownik", null)
                        .WithMany()
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
