using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using WorkTimeTracker.Data;
using WorkTimeTracker.Models;
using WorkTimeTracker.Utils;

namespace WorkTimeTracker.Services
{
    /// <summary>
    /// EF Core backed data service. Provides CRUD operations using SQLite via WorkTimeContext.
    /// This service is optional and can be used instead of file-based DataService.
    /// </summary>
    public class EfDataService : WorkTimeTracker.Interfaces.IDataService
    {
        private readonly WorkTimeContext _context;

        public EfDataService(WorkTimeContext context)
        {
            _context = context;
            _context.Database.EnsureCreated();
        }

        public async Task<List<Pracownik>> WczytajPracownikow(string nazwaPliku = "pracownicy.json")
        {
            return await _context.Pracownicy.AsNoTracking().ToListAsync();
        }

        public async Task ZapiszPracownika(Pracownik pracownik, int id)
        {
            var exists = await _context.Pracownicy.FindAsync(id);
            if (exists == null)
            {
                // ensure Id is set to provided id if possible
                pracownik.Id = id;
                _context.Pracownicy.Add(pracownik);
            }
            else
            {
                _context.Entry(exists).CurrentValues.SetValues(pracownik);
            }

            await _context.SaveChangesAsync();
        }

        public async Task AktualizujPracownika(Pracownik pracownik)
        {
            if (pracownik == null) throw new ArgumentNullException(nameof(pracownik));
            // Reuse ZapiszPracownika logic: ensure record exists and update
            await ZapiszPracownika(pracownik, pracownik.Id);
        }

        public async Task UsunPracownika(int id)
        {
            var p = await _context.Pracownicy.FindAsync(id);
            if (p != null)
            {
                _context.Pracownicy.Remove(p);
                await _context.SaveChangesAsync();
            }
        }

        public async Task<System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<RejestrCzasu>>> WczytajRejestry(string nazwaPliku = "rejestry.json")
        {
            var list = await _context.Rejestry.AsNoTracking().ToListAsync();
            var dict = list.GroupBy(r => r.PracownikId).ToDictionary(g => g.Key, g => g.ToList());
            return dict;
        }

        public async Task DodajRejestrDlaPracownika(int pracownikId, RejestrCzasu rejestr)
        {
            // attach foreign key
            var entry = new RejestrCzasu(rejestr.Data, rejestr.LiczbaGodzin, rejestr.CzyUrlop, rejestr.CzyNadgodziny)
            {
                // Id is generated by DB if 0
            };

            // set shadow FK
            _context.Entry(entry).Property("PracownikId").CurrentValue = pracownikId;
            _context.Rejestry.Add(entry);
            await _context.SaveChangesAsync();
        }

        // interface methods are implemented by the methods above
    }
}